# Generated by Django 4.2.6 on 2023-10-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmationtoken',
            name='token',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
    ]
