# Generated by Django 4.2.6 on 2023-10-31 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emailconfirmationtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmationtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailconfirmationtoken',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailconfirmationtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
